version: '3'
services:
  ### Posgres database for Inventory
  db-car-inventory:
    container_name: db-car-inventory
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: car_inventory_db
      POSTGRES_USER: josefontalvo
      POSTGRES_PASSWORD: Test123
    ports:
      - 5431:5431
    expose:
      - 5431
    command: -p 5431

  ### postgres database for orders or booking
  db-booking_db:
    container_name: db-booking_db
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: booking_db
      POSTGRES_USER: josefontalvo
      POSTGRES_PASSWORD: Test123
    ports:
      - 5435:5435
    expose:
      - 5435
    command: -p 5435

  ### Posgres database for payments
  db-payments:
    container_name: db-payments
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: payments_db
      POSTGRES_USER: josefontalvo
      POSTGRES_PASSWORD: Test123
    ports:
      - 5433:5433
    expose:
      - 5433
    command: -p 5433
  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim:${TAG:-latest}
    container_name: zipkin
    # Environment settings are defined here https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#environment-variables
    environment:
      - STORAGE_TYPE=mem
      # Uncomment to enable self-tracing
      # - SELF_TRACING_ENABLED=true
      # Uncomment to increase heap size
      # - JAVA_OPTS=-Xms128m -Xmx128m -XX:+ExitOnOutOfMemoryError
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411
